CREATE TABLE IF NOT EXISTS ``archive_{{ board }}`` (
  `id` int(11) UNSIGNED NOT NULL,
  `snippet` text NOT NULL,
  `lifetime` int(11) NOT NULL,
  `files` mediumtext NOT NULL,

 `thread` int(11) DEFAULT NULL,
 `subject` varchar(100) DEFAULT NULL,
 `email` varchar(30) DEFAULT NULL,
 `name` varchar(35) DEFAULT NULL,
 `trip` varchar(80) DEFAULT NULL,
 `capcode` varchar(50) DEFAULT NULL,
 `body` text NOT NULL,
 `body_nomarkup` text,
 `time` int(11) NOT NULL,
 `bump` int(11) DEFAULT NULL,
 `num_files` int(11) DEFAULT 0,
 `filehash` text CHARACTER SET ascii,
 `password` varchar(20) DEFAULT NULL,
 `ip` varchar(39) CHARACTER SET ascii NOT NULL,
 `sticky` int(1) NOT NULL,
 `locked` int(1) NOT NULL,
 `cycle` int(1) NOT NULL,
 `sage` int(1) NOT NULL,
 `embed` text,
 `slug` varchar(256) DEFAULT NULL,
  UNIQUE KEY `id` (`id`),
  KEY `lifetime` (`lifetime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
